pipeline:
  static-analysis:
    group: build
    image: openjdk:8
    commands:
      - ./gradlew findbugsMain

  build:
    group: build
    image: openjdk:8
    commands:
      - ./gradlew clean build

  request-deploy:
    image: docker.heed-dev.io/drone-k8s-deploy
    pull: true
    method: jenkins
    secrets: [ecr_access_key, ecr_secret_key, jenkins_dev_ci_username, jenkins_dev_ci_token]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
      branch: [develop, master]
