jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/project
    branches:
      only:
        - develop
    steps:
      - checkout:
                path: ~/project
      - run: ./gradlew test
